//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOrnek4EntityFrameworkConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int LessonsId { get; set; }
        public string LessonsName { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
